name=Rudesheim-Embedded-Board-Arduino
version=0.0.1
author=test
maintainer=test
sentence=Rudesheim layer 2: Board interface implementation for Arduino-API compatible devices.
category=Other
url=
architectures=*
depends=Rudesheim-Embedded-Base
